"use strict";
var core_1 = require('@angular/core');
exports.Component = core_1.Component;
exports.ElementRef = core_1.ElementRef;
exports.ViewChild = core_1.ViewChild;
exports.ViewContainerRef = core_1.ViewContainerRef;
exports.DynamicComponentLoader = core_1.DynamicComponentLoader;
exports.ComponentRef = core_1.ComponentRef;
var settings_actions_1 = require('./settings.actions');
exports.SettingsActions = settings_actions_1.SettingsActions;
var settings_model_1 = require('./settings.model');
exports.SettingsModel = settings_model_1.SettingsModel;
var settings_state_1 = require('./settings.state');
exports.SettingsState = settings_state_1.SettingsState;
var settings_views_1 = require('./settings.views');
exports.SettingsViews = settings_views_1.SettingsViews;
var sam_component_1 = require('../../sam/sam.component');
exports.Sam = sam_component_1.Sam;
//# sourceMappingURL=settings.exports.js.map